AllCops:
  TargetRubyVersion: 2.7.5
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-rspec
  - rubocop-performance

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 27

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "*.gemspec"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 11

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

RSpec/BeEq:
  Enabled: false
