# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec)

task default: %i[examples unit integration]

RSpec::Core::RakeTask.new(:unit) do |spec|
  spec.pattern = 'spec/unit/*_spec.rb'
end

desc 'Run examples in parallel'
task :examples do
  system 'parallel_split_test spec/examples/*_spec.rb'
end

desc 'Run integration tests in parallel'
task :integration do
  system 'parallel_split_test spec/integration/*_spec.rb'
end
